Add debug pages for missing vendor prefixes, inactive and deprecated CSS properties.
mathiasbynens/css-dbg-stories pull request #8
Opened 2022-06-07 08:26 UTC by Khukhunashvili

This CL adds debug pages for missing vendor prefixes, inactive and deprecated CSS properties.

2022-06-07 08:55 UTC, OrKoN approved these changes

2022-06-07 13:28 UTC, mathiasbynens requested changes
LGTM with a nit, happy to merge once addressed

2022-06-07 13:28 UTC, mathiasbynens commented on deprecated-css.html
> +<p><strong>grid-container</strong> here is using <span>grid-gap</span> property, which was renamed to <span>'gap'</span> in CSS3</p>
nit: The semantically correct element to use instead of `<strong>` and `<span>` on this line is `<code>`.

2022-06-07 13:28 UTC, mathiasbynens commented on inactive-css.html
> +<p><strong>wrapper</strong> class here is using <span>flex-wrap</span>: nowrap rule, therefore <span>'align-content'</span> has no effect. <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/al
Same here

2022-06-07 13:28 UTC, mathiasbynens commented on missing-vendor-prefixes.html
> +<p><strong>div</strong> element here has <span>transition</span> property, but has no vendor-prefixed rules. <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/transition">Learn More</a> </p>
Same here :)

2022-06-08 08:29 UTC, Khukhunashvili commented
Thank you, Mathias. I have updated the CL. Please take another look. ☺️

2022-06-08 09:29 UTC, mathiasbynens approved these changes

2022-06-08 09:29 UTC, merged